language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer self-update
    - composer install
    - composer require --dev --no-update phpunit/phpunit:@stable phpunit/php-code-coverage:@dev
    - composer update phpunit/php-code-coverage

script:
    - ./vendor/bin/phpunit --coverage-text

notifications:
    email: false
